### Cleanup temporary files generated by env_logic.py
### Reset to initialised environment

import os
import glob
import shutil

fileList = glob.glob('php/src/index_*.php')
flag_file = ('php/src/flag.txt')
dbLive = glob.glob('data/*.sql')
dbOrig = glob.glob('data/backup/*.sql')

dataWD = "C:\\Users\\roberac_adm\\rlctf_arena\\data"

def indexPHP():
    try:
        for file in fileList:
            os.remove(file)
    except OSError as e:
        print(e.strerror)

def flagFile():
    try:
        os.remove(flag_file)
    except OSError as e:
        print(e.strerror)
    try:
        with open(flag_file, 'x') as flag:
            flag.write("")
    except OSError as e:
        print(e.strerror)

def DB():
    try:
        for dbL in dbLive:
            os.remove(dbL)
    except OSError as e:
        print(e.strerror)
    try:
        for dbO in dbOrig:
            shutil.copyfile(dbO, dataWD)
            print(dbO)
    except shutil.Error as e: 
        print(e.strerror)



indexPHP()
flagFile()
#DB()
