# Configurations for firewall
# Install Modsecurity in a Docker container;


### TODO nginx reverse proxy with WAF - see following for setup tutorial
#https://github.com/janikvonrotz/nginx-modsecurity-crs
#https://janikvonrotz.ch/2020/02/26/nginx-waf-with-modsecurity-and-owasp-crs/